### ISSUE TITLE
Getting started?

### ISSUE THREAD

**Issue by LukeOwlclaw** [ElliottBrand/BlazorForum#29]
Thanks for your greate work and even more thanks for sharing it! How to get started with this cool forum?

By chance I found: https://blazorforums.net/forums/

You should definitely mention that in the README.md. However, it did not solve my problem. (A search feature would be so awesome!)

I am missing the first getting started steps. The "Database Setup Notes" is a good start, but actually it is not necessary because you can do that in the browser when you first launch the project.

What I fail to understand: How can I set the ``apiKey`` for the `SendGridClient`? It seems that it can be set via an admin page. But to login as admin, I need to create a user. Which will send an email. Which will fail because I have no ``apiKey`` configured. Sound like the chicken egg problem, doesn't it? Do I have to write my key manually into the database?

**Comment by ElliottBrand** [comment]
The easiest thing at the moment would be to mark the first user as approved in the database after the registration by going to the AspNetUsers table and setting the EmailConfirmed column to True. During registration, the first user would automatically be assigned to the Administrator role, so that first user will be able to access the admin area right away. It may have been easier if the first user's email was automatically approved, and that would make sense as an improvement, but since it was only for the first user during setup, I didn't see it as a big deal to adjust the value in the database once.

Most of this forum was built kind of as an experimental thing when Blazor first came out. Blazor Server was just released and Blazor WebAssembly wasn't even released yet. There are several things I'd do differently in it now and no one else really joined in to start contributing and improving it, and I haven't had time, so it is what it is. It does function and as you mention, it's running at blazorforums.net for Blazor developers to help each other out with general Blazor questions. However, it has no funding, so it likely won't receive a lot of improvements anytime soon. So, please keep that in mind if you're planning on using it for anything important. This was why I never added any versioning to it or pushed it out an official production release.

**Comment by LukeOwlclaw** [comment]
Thanks for your response and your help! I totally understand.
